### ISSUE TITLE
读后感

### ISSUE THREAD

**Issue by hotfireeagle** [airen/CSS3#1]
首先感谢大漠老师花费大量的时间铸就了此书，它很让我对css3新出现的特性有了更加深刻的理解。这本书详细介绍了各个css3特性，而且关于每个特性都用了挺多代码实例去讲解，自己动手敲这些代码的时候，更加能够加深关于该特性的理解。希望这个优点能够继续延续下去。   
关于第二版，希望可以看到更多关于下面这些方面的知识点:
+ 关于css属性是否具有继承性问题
+ 关于移动端主流浏览器的兼容性问题

**Comment by stellar91** [comment]
第8章CSS3伸缩布局盒模型个人认为只需保留新版本的Flexbox模型，也就是只保留8.4节，从我个人开发来讲，如果考虑兼容性，就不使用伸缩盒模型，如果不考虑兼容性，就直接使用最新版的Flexbox。

**Comment by wuyaoftd** [comment]
没看过 想看...

**Comment by willyang90** [comment]
从基础入门到深入，很详细，可以当做工具书，很适合新手，没事读读也能获得一定提高

**Comment by WeideMo** [comment]
通读过全书的读者，基本全量覆盖了CSS中的绝大多数的属性和用法，例子典型清晰，代码可读易懂，帮助前端新人从入门到精通，哪怕我是有若干年经验的前端开发者，但是也阅读之前也是不尽了解网页样式的处理和相关属性，个人以为，第一版的图解完全适合各个阶段的开发者。该书水分量极低，可以说是针对CSS学习的权威指南，多次查阅结合项目实际应用，可以逐渐巩固知识点熟练度，以上肺腑之言，请有心者点个赞[good]
