### ISSUE TITLE
关于CSS3伸缩盒模型

### ISSUE THREAD

**Issue by zstaring** [airen/CSS3#2]
第8章CSS3伸缩布局盒模型个人认为只需保留新版本的Flexbox模型，也就是只保留8.4节，从我个人开发来讲，如果考虑兼容性，就不使用伸缩盒模型，如果不考虑兼容性，就直接使用最新版的Flexbox。

**Comment by airen** [comment]
这里的大纲还是第一版本的大纲，第二版本的大纲会在这周更新出来。
