### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by Michael1117** [airen/CSS3#6]
1，首先大漠老师的水平是毋容置疑的，毕竟这么多年的经验了，但是《图解CSS3》技巧性的地方太少了，例如怎样清浮动，CSS滑动门怎样弄，CSS精灵等等，这一点需要向《CSS Mastery》学习。
2，个人感觉《图解CSS3》只是把新特性介绍了一遍，而新特性文档上都有，还有就是有些章节过于啰嗦，我想大部分人关心的是在实际的开发中遇到问题后怎样解决，总之这本书在实际开发中用处不大，干货较少，希望下一版可以改进。

**Comment by airen** [comment]
@Michael1117 首先感谢老朋友给我提的意见。而且意见也非常的中肯。的确是有这方面的现象，第一版本主要还是以介绍CSS属性的，而且这方面的介绍在规范中能找到。从这方面来看实用价值的确不大。

下面不过是我自己的几个看法：

- 对于CSS3里面的一些小技巧，在第二版本的示例中会略为增强，尽量结合实际业务来展开
- 这次每个章节的内容文字组织会尽量的精减，以实质性的内容为出发点
- 希望这本书能当作手册查询

对于小技巧，希望有更多的同学能一起参与，因为CSS的一些新性还是主要来解决一些以前依赖于图片解决的事情。不过我自己也会多思考一下。

再次感觉老朋友的意见，谢谢！！！
