### ISSUE TITLE
小建议以及读后感

### ISSUE THREAD

**Issue by lvxue-shirly** [airen/CSS3#7]
*期待内容安排能由易到难，由浅入深，前面的章节是基础，后面的章节解读一些规范
*希望这本书的目录可以以一些问题现象作为索引结合理论与实际开发
*最后祝大漠老师的这本书成为教科书的典范，学css这一本就足够了

**Comment by airen** [comment]
其实CSS发展到现在，已没有连贯性一说了，都划分成各个模块了，第二版本将以模块的划分为前提。从中也涉及到了先易后难的节奏，当然阅读的时候可以选择自己感兴趣的点开始。另外书中还是会延续第一版本的风格，语法解读和实例并行，这次的实例可能会结合一些实战中会碰到的示例为主。

**Comment by annilq** [comment]
个人建议可以多一些属性的应用场景以及应用技巧的讲解，以及整个项目的css编写规范和环境还很少有有一些书总结道，实战来讲，第一本书的源代码demo已经很惊艳
